"""
This type stub file was generated by pyright.
"""

from tkinter import Event, EventType, Grid, Misc, Pack, Place, Text
from tkinter.ttk import Frame, Style
from typing import Any, Dict, Iterable, NamedTuple, Optional
from ttk_text.utils import parse_padding

"""
This type stub file was generated by pyright.
"""
__all__ = ["ThemedText", "ThemedTextFrame"]
_UPDATE_STYLE_ONLY_EVENTS = ...
_TRANSITION_STATE_EVENTS = ...
class BoundText(NamedTuple):
    """
    A bound text widget tuple for managing text widgets and their original instances.

    :ivar widget: Original widget instance, used to determine which widget's event when receiving events
    :ivar proxy: Text widget instance, which may be the super of the widget or the widget itself
    """
    widget: Text
    proxy: Text
    ...


class BoundWidget(NamedTuple):
    """
    A bound widget tuple for managing widgets and their state penetration.

    :ivar instance: Widget instance
    :ivar penetration_state: Whether to allow state penetration to ThemedTextFrame
                        True: Widget events modify the frame state (e.g., decorative components)
                        False: Only bind events, do not modify frame state (e.g., scrollbars)
    """
    instance: Misc
    penetration_state: bool
    ...


class ThemedTextFrame(Frame):
    """
    A themed text frame providing ttk-style text container.

    This class is a ttk Frame responsible for managing bound text widgets and state transitions,
    automatically updating styles through bound event listeners.

    Features:
        - Supports themed text widget styling
        - Automatically handles focus, hover, and pressed states
        - Supports binding multiple widgets for complex interaction states

    State Management:
        - focus: Activated when the widget gains focus
        - hover: Activated when mouse hovers
        - pressed: Activated when mouse is pressed

    Important Note:
        The frame automatically updates its own state. For example, when the mouse hovers over other widgets
        inside the frame, the frame will automatically remove its own hover state. Since there is no direct
        way to detect this behavior, all internal components need to be event-bound to ensure styles are
        correctly updated to the text widget. This is the purpose of `penetration_state=False`: even if
        widget events don't modify the frame state, they need to be bound to trigger style updates.

    Example:
        .. code-block:: python

            # Create a themed text frame
            frame = ThemedTextFrame(root)
            frame.pack(fill="both", expand=True)

            # Configure grid weights to make the text area expandable
            frame.grid_rowconfigure(0, weight=1)
            frame.grid_columnconfigure(0, weight=1)

            # Create a text widget and bind it to the frame
            text = Text(frame)
            frame.bind_text(text)
            text.grid(row=0, column=0, sticky="nsew")

            # Add a scrollbar and bind it (non-penetrating state)
            scrollbar = Scrollbar(frame)
            scrollbar.grid(row=0, column=1, sticky="ns")
            frame.bind_widget(scrollbar, penetration_state=False)

    Style Options:
        - style: ttk style name (default="ThemedText.TEntry")
        - class_: Widget class name (default="ThemedText")
    """
    def __init__(self, master: Optional[Misc] = ..., **kwargs) -> None:
        """
        Initialize a ThemedTextFrame instance.

        :param master: Parent widget, default is None
        :param kwargs: Configuration options passed to Frame

        .. note::
            If style is not specified, "ThemedText.TEntry" will be used.
            If class_ is not specified, "ThemedText" will be used.
        """
        ...
    
    def bind_widget(self, widget: Misc, *, penetration_state: bool = ...):
        """
        Bind a widget to the frame so its events can trigger style updates.

        :param widget: Widget instance to bind
        :param penetration_state: Whether widget events modify the frame state

        .. note::
            - For functional components like scrollbars, set penetration_state=False
              so widget events do not modify the frame state but still trigger style updates
            - For decorative components, set penetration_state=True
              so widget events modify the frame state and trigger style updates

            Default is False, suitable for most functional components.
            Since the frame automatically updates its own state, all internal components
            need to be event-bound to ensure styles are correctly updated to the text widget.
            This is the main purpose of penetration_state=False.
        """
        ...
    
    def bind_text(self, text: Text, proxy: Optional[Text] = ...):
        """
        Bind a text widget to the frame.

        :param text: Text widget instance
        :param proxy: Optional proxy text (can be a super widget of text)

        .. note::
            This method configures the text widget with a flat style (no border or highlight),
            and binds it to the frame to receive state change events.
        """
        ...
    
    def update_style(self):
        ...
    


class ThemedText(Text):
    """
    A themed text widget combining Tkinter Text with ttk Frame styling.

    This widget provides native Tkinter Text functionality with ttk theme support.
    Inherits from `tkinter.Text` while embedding a ThemedTextFrame for style management.

    Style Elements:
        - Style name: 'ThemedText.TEntry' (configurable via style parameter)
        - Theme states: [focus, hover, pressed] with automatic state transitions

    Default Events:
        <FocusIn>       - Activates focus styling
        <FocusOut>      - Deactivates focus styling
        <Enter>         - Applies hover state
        <Leave>         - Clears hover state
        <ButtonPress-1> - Sets pressed state (left mouse down)
        <ButtonRelease-1> - Clears pressed state (left mouse up)
        <<ThemeChanged>> - Handles theme reload events

    Geometry Management:
        Proxies all ttk.Frame geometry methods (pack/grid/place) while maintaining
        native Text widget functionality. Use standard geometry managers as with
        regular ttk widgets.

    Inheritance Chain:
        ThemedText → tkinter.Text → tkinter.Widget → tkinter.BaseWidget → object
    """

    def __init__(self, master: Optional[Misc] = ..., **kwargs) -> None:
        """
        Initialize a themed text widget.

        :param master: Parent widget (default=None)
        :param style: ttk style name (default='ThemedText.TEntry')
        :param class_: Widget class name (default='ThemedText')
        :param kw: Additional Text widget configuration options

        .. note::
            Extract frame-related configuration from kwargs (class, style, relief, padding, borderwidth),
            remaining configuration is passed to the Text widget.
        """
        self.frame: ThemedTextFrame
        ...
    
    def __str__(self) -> str:
        """
        Return the string representation of the frame.

        :return: String representation of the frame
        """
        ...
    


def example():
    ...

if __name__ == "__main__":
    ...
