"""
This type stub file was generated by pyright.
"""

from ttk_text import ThemedText

"""
This type stub file was generated by pyright.
"""
__all__ = ["ScrolledText"]
class ScrolledText(ThemedText):
    """
    A replacement for tkinter.scrolledtext with enhanced theming support.

    Inherits from ThemedText and supports automatic vertical/horizontal scrollbars.
    This class provides a modern alternative to the standard `tkinter.scrolledtext`,
    with improved theming capabilities and customization options.

    Args:
        master: Parent widget container.
        vertical (bool): Whether to enable the vertical scrollbar (default: True).
        horizontal (bool): Whether to enable the horizontal scrollbar (default: False).
        **kw: Additional arguments passed to ThemedText.

    Attributes:
        vbar (Scrollbar): Vertical scrollbar instance (exists when vertical=True).
        hbar (Scrollbar): Horizontal scrollbar instance (exists when horizontal=True).
        corner (Frame): Corner frame for the scrollbars (exists when vertical=True and horizontal=True).
    """
    def __init__(self, master=..., *, vertical=..., horizontal=..., **kw) -> None:
        ...
    


def example():
    ...

if __name__ == "__main__":
    ...
