"""
This type stub file was generated by pyright.
"""

from typing import NamedTuple, Optional, Tuple, Union

"""
This type stub file was generated by pyright.
"""
ScreenDistance = Union[float, str]
class Padding(NamedTuple):
    left: ScreenDistance
    top: ScreenDistance
    right: ScreenDistance
    bottom: ScreenDistance
    def to_padx(self) -> Tuple[ScreenDistance, ScreenDistance]:
        ...
    
    def to_pady(self) -> Tuple[ScreenDistance, ScreenDistance]:
        ...
    


def parse_padding(padding: Union[ScreenDistance, Tuple[ScreenDistance, ...], None]) -> Optional[Padding]:
    ...

