from typing import Any  # noqa: INP001


def make_table(headers: list[Any], rows: list[list[Any]]):
    return "\n".join(
        [
            f"| {' | '.join(headers)} |",
            f"| {' | '.join(['---'] * len(headers))} |",
            *[f"| {' | '.join(row)} |" for row in rows],
        ],
    )


def make_url(text: str, url: str) -> str:
    return f"[{text}]({url})"


def make(notices: list[Any]):
    return f"""
<!-- Generated by 'uv run scripts/docs/generate_os_notices.py', DO NOT DIRECTLY EDIT THIS FILE. -->
<!-- The template is located at 'docs/os_notices_template.py' -->
<!-- markdownlint-disable -->
<!-- @formatter:off -->

# 开源声明

{
        make_table(
            ["开源项目", "许可证", "版权声明"],
            [
                [
                    make_url(notice["name"], notice["repository"]) if "repository" in notice else notice["name"],
                    make_url(notice["license"], notice["license-url"]),
                    "<br />".join(notice["copyrights"]),
                ]
                # noinspection PyUnresolvedReferences
                for notice in notices
            ],
        )
    }
""".lstrip()
