name: Release App

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit
    name: Test
  build-apps:
    uses: ./.github/workflows/build_all.yml
    name: Build All Apps
    needs: test
    secrets: inherit
    with:
      build-windows-installer: true
      build-windows-portable: true
      build-python3-zipapp: true
      build-python3-wheel: true
  release:
    name: Release
    needs: build-apps
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download All Packages
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - name: Release Upload Assets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.event.release.tag_name }} \
            *-portable.zip \
            *-setup.exe \
            *.pyzw \
            *.whl \
            --clobber --repo $GITHUB_REPOSITORY
