name: Test

on:
  push:
    branches:
      - "releases/**"
    paths:
      - "**.py"
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
    branches:
      - master
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    runs-on: windows-latest # TODO: Use ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13", "3.14t"]
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Update .python-version file
        run: uv python pin ${{ matrix.python-version }}
      - name: Test with pytest
        run: uv run poe test
