name: Test

on:
  push:
    branches:
      - "releases/**"
    paths:
      - "**.py"
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    runs-on: windows-latest # TODO: Use ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13", "3.14t"]
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: uv sync -p ${{ matrix.python-version }}
      - name: Test with pytest
        run: uv run pytest
